#ifndef AUTO_COMPLETE_ERROR_H
#define AUTO_COMPLETE_ERROR_H

typedef enum {
    ERR_NONE = 0,
    ERR_MISSING_ENV_COMP_LINE = -2,
    ERR_MISSING_ENV_COMP_POINT = -3,
    ERR_INVALID_ENV_COMP_POINT = -4,
    ERR_INVALID_CLI_ARGUMENT = -5,
    ERR_NO_DATABASE_CONNECTION = -20,
    ERR_INVALID_CMD_NAME = -21,
    ERR_INVALID_CMD = -22,
    ERR_INVALID_ALIAS = -23,
    ERR_INVALID_ARG = -24,
    ERR_INVALID_OPT = -25,
    ERR_READ_FILE = -26,
    ERR_DATABASE_SCHEMA_VERSION_MISMATCH = -27,
    ERR_OPEN_DATABASE = -101,
    ERR_DATABASE_PRAGMA = -102,
    ERR_DATABASE_CREATE_TABLE = -104,
    ERR_SQLITE_ERROR = -105,
} bce_error_t;

char* get_bce_error_msg(bce_error_t err);

#endif // AUTO_COMPLETE_ERROR_H
