#ifndef AUTO_COMPLETE_ERROR_H
#define AUTO_COMPLETE_ERROR_H

enum {
    ERR_MISSING_DATA = -1,
    ERR_MISSING_ENV_COMP_LINE = -2,
    ERR_MISSING_ENV_COMP_POINT = -3,
    ERR_INVALID_ENV_COMP_POINT = -4,
    ERR_INVALID_CLI_ARGUMENT = -5,
    ERR_OPEN_DATABASE = -101,
    ERR_DATABASE_PRAGMA = -102,
    ERR_DATABASE_SCHEMA = -103,
    ERR_DATABASE_CREATE_TABLE = -104,
    ERR_SQLITE_ERROR = -105,
};

#endif // AUTO_COMPLETE_ERROR_H
